server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://39.97.169.2:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  redis:
    database: 1
    host: 39.97.169.2
    port: 6379
    password: redis

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl       #日志打印
